import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import NavBar from "./NavBar";
import { Suspense } from "react";


const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ['latin'],
})

const pacifico = localFont({
  variable: "--font-pacifico",
  src: '../public/fonts/Pacifico.ttf',
})

export const metadata: Metadata = {
  title: "Erfan Poursoleimani",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${pacifico.variable} ${roboto.variable} antialiased`}
        style={{}}
      >
        <NavBar/>
        <main>
          <Suspense fallback={<p>Loading ...</p>}>
            {children}
          </Suspense>
        </main>
      </body>
    </html>
  );
}
